### ISSUE TITLE
Problemas ao iniciar o projeto

### ISSUE THREAD

**Issue by lvlofenix** [marcelohenrique95/test-angular#1]
Olá pessoal, tudo bem?

Seguir com os passos indicados no _readme_ do repositório porem não obtive sucesso ao iniciar o projeto.

Essas são minhas Dependências instaladas 
![image](https://user-images.githubusercontent.com/10848573/126498388-d15d0267-5508-4ca4-96a1-28dc34703c04.png)

O que podemos fazer para solucionar o problema?

Segue log do terminal 

```O Windows PowerShell
Copyright (C) Microsoft Corporation. Todos os direitos reservados.

Instale o PowerShell mais recente para obter novos recursos e aprimoramentos! https://aka.ms/PSWindows

PS C:\Users\Lucas Vinicius\Documents\test-angular> npm i
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> core-js@3.15.1 postinstall C:\Users\Lucas Vinicius\Documents\test-angular\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> @angular/cli@12.1.2 postinstall C:\Users\Lucas Vinicius\Documents\test-angular\node_modules\@angular\cli
> node ./bin/postinstall/script.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1336 packages from 1164 contributors and audited 1343 packages in 46.876s

88 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\Lucas Vinicius\Documents\test-angular> npm start

> testangular@0.0.0 start C:\Users\Lucas Vinicius\Documents\test-angular
> ng serve

⠋ Generating browser application bundles (phase: setup)...Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @ng-bootstrap/ng-bootstrap : es2015 as esm2015
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |      Size
vendor.js             | vendor        |   3.11 MB
styles.css, styles.js | styles        | 533.76 kB
polyfills.js          | polyfills     | 509.09 kB
main.js               | main          |  21.58 kB
runtime.js            | runtime       |   6.58 kB

                      | Initial Total |   4.16 MB

Build at: 2021-07-21T13:35:33.708Z - Hash: dffbef2710938bca1633 - Time: 26554ms

./src/polyfills.ts:4:0-32 - Error: Module not found: Error: Can't resolve '@angular/localize/init' in 'C:\Users\Lucas Vinicius\Documents\test-angular\src'



** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

✔ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2021-07-21T13:35:35.006Z - Hash: 107e36c47260e3c83ed8 - Time: 779ms

./src/polyfills.ts:4:0-32 - Error: Module not found: Error: Can't resolve '@angular/localize/init' in 'C:\Users\Lucas Vinicius\Documents\test-angular\src``` 

___ ``

**Comment by marcelohenrique95** [comment]
Bom dia Lucas, tudo bom ?
Tente excluir a node modules e package-lock.json e rode novamente o npm install
Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Lucas ***@***.***>
Enviado:quarta-feira, 21 de julho de 2021 09:41
Para: ***@***.***>
***@***.***>
Assunto: [marcelohenrique95/test-angular] Problemas ao iniciar o projeto (#1)


Olá pessoal, tudo bem?

Seguir com os passos indicados no readme do repositório porem não obtive sucesso ao iniciar o projeto.

Segue log do terminal

`O Windows PowerShell
Copyright (C) Microsoft Corporation. Todos os direitos reservados.

Instale o PowerShell mais recente para obter novos recursos e aprimoramentos! https://aka.ms/PSWindows

PS C:\Users\Lucas Vinicius\Documents\test-angular> npm i
npm WARN read-shrinkwrap This version of npm is compatible with ***@***.***, but package-lock.json was generated for ***@***.*** I'll try to do my best with it!

***@***.*** postinstall C:\Users\Lucas Vinicius\Documents\test-angular\node_modules\core-js
node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:

https://opencollective.com/core-js
https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

@***@***.*** postinstall C:\Users\Lucas ***@***.***\cli
node ./bin/postinstall/script.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ***@***.*** (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for ***@***.***: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ***@***.*** (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for ***@***.***: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1336 packages from 1164 contributors and audited 1343 packages in 46.876s

88 packages are looking for funding
run npm fund for details

found 1 moderate severity vulnerability
run npm audit fix to fix them, or npm audit for details
PS C:\Users\Lucas Vinicius\Documents\test-angular> npm start

***@***.*** start C:\Users\Lucas Vinicius\Documents\test-angular
ng serve

⠋ Generating browser application bundles (phase: setup)...Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @ng-bootstrap/ng-bootstrap : es2015 as esm2015
✔ Browser application bundle generation complete.

Initial Chunk Files | Names | Size
vendor.js | vendor | 3.11 MB
styles.css, styles.js | styles | 533.76 kB
polyfills.js | polyfills | 509.09 kB
main.js | main | 21.58 kB
runtime.js | runtime | 6.58 kB

                  | Initial Total |   4.16 MB



Build at: 2021-07-21T13:35:33.708Z - Hash: dffbef2710938bca1633 - Time: 26554ms

./src/polyfills.ts:4:0-32 - Error: Module not found: Error: Can't resolve ***@***.***/localize/init' in 'C:\Users\Lucas Vinicius\Documents\test-angular\src'

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

✔ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2021-07-21T13:35:35.006Z - Hash: 107e36c47260e3c83ed8 - Time: 779ms

./src/polyfills.ts:4:0-32 - Error: Module not found: Error: Can't resolve ***@***.***/localize/init' in 'C:\Users\Lucas Vinicius\Documents\test-angular\src'`

Essas são minhas dependencias instaladas
[image]<https://user-images.githubusercontent.com/10848573/126498388-d15d0267-5508-4ca4-96a1-28dc34703c04.png>

O que podemos fazer para solucionar o problema?
Abs.

**Comment by lvlofenix** [comment]
Olá pessoal :) td certo?

Fiz os procedimentos informados mas não deu certo, pesquisando sobre o assunto encontrei esses 2 links:
 
https://angular.io/api/localize/init
https://angular.io/guide/migration-localize

que me ajudou a entender melhor o conceito da importação com falha e por isso bastou comenta-la no arquivo
`polyfills.ts` linha 4

```
...
...
/***************************************************************************************************
 * Load `$localize` onto the global scope - used if i18n tags appear in Angular templates.
 */
//import '@angular/localize/init';

/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can ad
...
...
```

Consegui rodar o projeto!!

Obrigado pela atenção Marcelo :) 
te encontro na próxima fase.

Boa sorte
abs!
